import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Room, RoomEvent, Track, type RemoteTrack, type RemoteTrackPublication, type RemoteParticipant } from 'livekit-client';
import { api, ApiError } from './api';
import { acceptSnapshot, buildTranscript, initialSessionState, voiceState, type Mode, type SessionState, type Snapshot, type TranscriptRow } from './state';
import { PlaybackAcknowledger } from './playback';

const SESSION_KEY='pickmate.session';
type StoredSession={id:string;token:string};
function storedSession():StoredSession|null{try{return JSON.parse(sessionStorage.getItem(SESSION_KEY)??'null')}catch{return null}}
function formatTime(utc:string){const date=new Date(utc);return Number.isNaN(date.valueOf())?'':date.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'})}
function errorText(error:unknown){return error instanceof ApiError?error.message:error instanceof Error?error.message:'Something went wrong.'}

export default function App(){
  const [state,setState]=useState<SessionState>(initialSessionState);
  const [mode,setMode]=useState<Mode>('fixture');
  const [health,setHealth]=useState<{live_ready:boolean;demo_enabled:boolean;missing_config:string[]} | null>(null);
  const [credential,setCredential]=useState<StoredSession|null>(()=>storedSession());
  const [room,setRoom]=useState<Room|null>(null);
  const roomRef=useRef<Room|null>(null);
  const [connected,setConnected]=useState(false);
  const [micEnabled,setMicEnabled]=useState(false);
  const [audioBlocked,setAudioBlocked]=useState(false);
  const [message,setMessage]=useState('');
  const [busy,setBusy]=useState(false);
  const [actionError,setActionError]=useState<string|null>(null);
  const [pollError,setPollError]=useState<string|null>(null);
  const [developerOpen,setDeveloperOpen]=useState(false);
  const [delay,setDelay]=useState(5000);
  const [ignoreCancellation,setIgnoreCancellation]=useState(false);
  const [failure,setFailure]=useState('');
  const stateRef=useRef(state);stateRef.current=state;
  const snapshot=state.snapshot;

  const applySnapshot=useCallback((incoming:Snapshot)=>setState(current=>acceptSnapshot(current,incoming)),[]);
  const playback=useMemo(()=>new PlaybackAcknowledger(async(responseId,status)=>{if(credential)applySnapshot(await api.playback(credential.id,credential.token,responseId,status))}),[credential,applySnapshot]);

  useEffect(()=>{api.health().then(h=>{setHealth(h);if(!h.live_ready)setMode('fixture')}).catch(e=>setActionError(errorText(e)))},[]);
  useEffect(()=>{if(!credential)return;let disposed=false;let inFlight=false;const poll=async()=>{if(inFlight)return;inFlight=true;try{const next=await api.snapshot(credential.id,credential.token);if(!disposed){applySnapshot(next);setPollError(null)}}catch(e){if(!disposed){if(e instanceof ApiError&&[401,404].includes(e.status)){sessionStorage.removeItem(SESSION_KEY);setCredential(null);setState(initialSessionState)}setPollError(errorText(e))}}finally{inFlight=false}};void poll();const timer=window.setInterval(poll,400);return()=>{disposed=true;window.clearInterval(timer)}},[credential,applySnapshot]);
  useEffect(()=>{if(snapshot?.mode!=='fixture'||snapshot.speech?.status!=='queued')return;playback.start(snapshot.speech.response_id)},[snapshot?.speech?.response_id,snapshot?.speech?.status,snapshot?.mode,playback]);
  useEffect(()=>()=>playback.stop(),[playback]);
  useEffect(()=>()=>{const active=roomRef.current;roomRef.current=null;void active?.disconnect();document.querySelectorAll<HTMLMediaElement>('[data-pickmate-audio]').forEach(el=>el.remove())},[]);

  const connectLive=useCallback(async(c:StoredSession)=>{
    const old=roomRef.current;if(old){roomRef.current=null;await old.disconnect()}document.querySelectorAll<HTMLMediaElement>('[data-pickmate-audio]').forEach(el=>el.remove());
    const details=await api.liveToken(c.id,c.token);const nextRoom=new Room({adaptiveStream:true,dynacast:true});
    nextRoom.on(RoomEvent.TrackSubscribed,(track:RemoteTrack,_pub:RemoteTrackPublication,_participant:RemoteParticipant)=>{if(track.kind===Track.Kind.Audio){const el=track.attach();el.dataset.pickmateAudio='remote';document.body.appendChild(el);void el.play().then(()=>setAudioBlocked(false)).catch(()=>setAudioBlocked(true))}});
    nextRoom.on(RoomEvent.TrackUnsubscribed,(track:RemoteTrack)=>track.detach().forEach(el=>el.remove()));
    nextRoom.on(RoomEvent.Disconnected,()=>{setConnected(false);setMicEnabled(false)});
    await nextRoom.connect(details.url,details.token);roomRef.current=nextRoom;setRoom(nextRoom);setConnected(true);
    try{await nextRoom.localParticipant.setMicrophoneEnabled(true);setMicEnabled(true)}catch(e){setActionError('Microphone access was denied. Allow microphone access in browser settings, then use the microphone button to retry.')}
  },[]);

  async function startSession(){setBusy(true);setActionError(null);try{const created=await api.create(mode);const c={id:created.session_id,token:created.token};sessionStorage.setItem(SESSION_KEY,JSON.stringify(c));setCredential(c);applySnapshot(created.snapshot);if(mode==='live')await connectLive(c)}catch(e){setActionError(errorText(e))}finally{setBusy(false)}}
  async function control(action:string){if(!credential)return;setBusy(true);setActionError(null);try{if(action==='end'){playback.stop();roomRef.current=null;await room?.disconnect();document.querySelectorAll<HTMLMediaElement>('[data-pickmate-audio]').forEach(el=>el.remove())}const next=await api.control(credential.id,credential.token,action);if(action==='end'){sessionStorage.removeItem(SESSION_KEY);setCredential(null);setRoom(null);setConnected(false);setState(initialSessionState)}else applySnapshot(next)}catch(e){setActionError(errorText(e))}finally{setBusy(false)}}
  async function reconnect(){if(!credential)return;setBusy(true);setActionError(null);try{applySnapshot(await api.control(credential.id,credential.token,'recover'));await connectLive(credential)}catch(e){setConnected(false);setActionError(errorText(e))}finally{setBusy(false)}}
  async function submitTurn(e:FormEvent){e.preventDefault();if(!credential||!message.trim())return;const text=message.trim();setMessage('');setBusy(true);try{applySnapshot(await api.turn(credential.id,credential.token,text))}catch(err){setActionError(errorText(err));setMessage(text)}finally{setBusy(false)}}
  async function toggleMic(){if(!room)return;try{const enabled=!micEnabled;await room.localParticipant.setMicrophoneEnabled(enabled);setMicEnabled(enabled);setActionError(null)}catch{setActionError('Microphone access was denied. Allow access in browser settings and try again.')}}
  async function injectFault(){if(!credential)return;try{applySnapshot(await api.faults(credential.id,credential.token,{lookup_delay_ms:delay,ignore_cancellation:ignoreCancellation,fail_provider:failure||null}));setActionError(null)}catch(e){setActionError(errorText(e))}}
  async function unlockAudio(){try{const els=[...document.querySelectorAll<HTMLMediaElement>('[data-pickmate-audio]')];await Promise.all(els.map(el=>el.play()));setAudioBlocked(false)}catch{setActionError('Audio output is still blocked. Check the site sound permission and try again.')}}

  const status=voiceState(snapshot,connected);
  const transcript=buildTranscript(snapshot?.events??[]);
  if(!snapshot)return <main className="welcome"><section className="start-card"><div className="brand-mark" aria-hidden="true">P</div><p className="kicker">Stockroom voice assistant</p><h1>Keep your hands on the work.</h1><p className="lede">PickMate listens for a pick, checks the bin, and records only what you confirm.</p>{(actionError||pollError)&&<ErrorBanner text={actionError||pollError||''}/>}<fieldset className="mode-picker"><legend>Session mode</legend><label><input type="radio" checked={mode==='fixture'} onChange={()=>setMode('fixture')}/><span><strong>Fixture</strong><small>Typed, repeatable, no speech</small></span></label><label className={!health?.live_ready?'disabled':''}><input type="radio" checked={mode==='live'} disabled={!health?.live_ready} onChange={()=>setMode('live')}/><span><strong>Live voice</strong><small>{health?.live_ready?'Microphone and realtime audio':`Unavailable${health?.missing_config?.length?' — missing configuration':''}`}</small></span></label></fieldset><button className="primary start" onClick={startSession} disabled={busy||!health}>{busy?'Starting…':'Start session'}</button><p className="privacy">The reconnect token stays in this browser tab and is removed when the session ends.</p></section></main>;

  return <div className="app-shell"><header><a className="brand" href="#main" aria-label="PickMate home"><span>P</span>PickMate</a><div className={`mode-badge ${snapshot.mode}`}>{snapshot.mode==='fixture'?'Fixture · typed only':'Live voice'}</div><div className="synthetic-badge">Synthetic inventory</div><button className="quiet" onClick={()=>setDeveloperOpen(v=>!v)} aria-expanded={developerOpen}>Developer</button></header>
    <main id="main" className="workspace"><section className="main-column"><VoicePanel status={status} provider={snapshot.provider.name} micMuted={snapshot.mode==='live'&&connected&&!micEnabled}/>{(actionError||pollError)&&<ErrorBanner text={actionError||pollError||''}/>} {audioBlocked&&<div className="notice"><span>Browser audio is paused until you allow playback.</span><button onClick={unlockAudio}>Enable audio</button></div>}{snapshot.mode==='live'&&(!connected||snapshot.provider.status==='failed')&&<div className="notice provider-failure"><span>{snapshot.provider.status==='failed'?'Voice provider failed. The current task is preserved.':'Voice room is disconnected. Reconnect to continue.'}</span><div><button onClick={reconnect} disabled={busy}>Reconnect voice</button><button onClick={()=>control('end')} disabled={busy}>End session</button></div></div>}<TaskCard snapshot={snapshot}/>
      {snapshot.mode==='fixture'&&<form className="turn-form" onSubmit={submitTurn}><label htmlFor="fixture-turn">Type what the worker says</label><div><input id="fixture-turn" value={message} onChange={e=>setMessage(e.target.value)} placeholder="e.g. Pick six blue cartons" disabled={snapshot.paused||busy}/><button className="primary" disabled={!message.trim()||busy||snapshot.paused}>Send turn</button></div><small>Fixture input is text only. Playback events are simulated and are not audio measurements.</small></form>}
      <div className="controls">{snapshot.mode==='live'&&<button className={micEnabled?'control active':'control'} onClick={toggleMic} disabled={!connected}><MicIcon off={!micEnabled}/><span>{micEnabled?'Mute mic':'Turn mic on'}</span></button>}<button className="control" onClick={()=>control(snapshot.paused?'resume':'pause')} disabled={busy}>{snapshot.paused?'Resume':'Pause'}</button><button className="control" onClick={()=>control('repeat')} disabled={busy}>Repeat</button>{snapshot.task&&!['committed','cancelled'].includes(snapshot.task.status)&&<button className="control" onClick={()=>control('cancel')} disabled={busy}>Cancel pick</button>}<button className="control danger" onClick={()=>control('end')} disabled={busy}>End session</button></div>
      <Transcript events={transcript}/><History snapshot={snapshot}/></section><Inventory items={snapshot.inventory}/></main>
    {developerOpen&&<DeveloperPanel snapshot={snapshot} demoEnabled={!!health?.demo_enabled} delay={delay} setDelay={setDelay} ignoreCancellation={ignoreCancellation} setIgnoreCancellation={setIgnoreCancellation} failure={failure} setFailure={setFailure} inject={injectFault} close={()=>setDeveloperOpen(false)}/>}</div>
}

function VoicePanel({status,provider,micMuted}:{status:string;provider:string;micMuted:boolean}){const title=micMuted?'Microphone muted':status[0].toUpperCase()+status.slice(1);return <section className={`voice-panel ${status} ${micMuted?'muted':''}`} aria-live="polite"><div className="voice-orb" aria-hidden="true"><i/><i/><i/></div><div><p>Assistant state</p><h2>{title}</h2><span>{micMuted?'Turn the microphone on to speak.':status==='listening'?'Ready for the next instruction.':status==='thinking'?'Checking the current request.':status==='speaking'?'Giving the next instruction.':status==='paused'?'Task held. Resume when ready.':status==='disconnected'?'Connection closed.':'Start when ready.'}</span></div><small>{provider}</small></section>}
function TaskCard({snapshot}:{snapshot:Snapshot}){const t=snapshot.task;const resolved=!!t&&['ready','awaiting_confirmation','committed'].includes(t.status);return <section className="task-card"><div className="section-head"><div><p>Current pick</p><h2>{t?.item?.name??'No active pick'}</h2></div><span className={`task-status ${t?.status??'empty'}`}>{t?.status?.replaceAll('_',' ')??'Waiting'}</span></div>{t?<div className="pick-grid"><div><small>Quantity</small><strong>{t.quantity}</strong></div><div><small>Bin</small><strong>{resolved?t.item.bin:'Pending'}</strong></div><div><small>Available</small><strong>{resolved?t.item.available:'—'}</strong></div></div>:<p className="empty-copy">Ask for an item and quantity to begin. Nothing is deducted until the exact pick is confirmed.</p>}</section>}
function Transcript({events}:{events:TranscriptRow[]}){return <details className="transcript" open><summary>Transcript <span>{events.length} entries</span></summary><div>{events.length===0?<p className="empty-copy">Conversation appears here as turns finish.</p>:events.map(row=><article key={row.key} className={row.status==='interrupted'?'interrupted':''}><div><strong>{row.speaker}</strong><time>{formatTime(row.utc)}</time></div><p>{row.text}</p><small>{row.status.replaceAll('_',' ')} · {row.evidence}</small></article>)}</div></details>}
function Inventory({items}:{items:Snapshot['inventory']}){return <aside className="inventory"><div className="section-head"><div><p>Stock</p><h2>Inventory</h2></div><span>{items.length}</span></div><div className="inventory-list">{items.length?items.map(item=><article key={item.sku}><div><strong>{item.name}</strong><small>{item.sku}</small></div><div><b>{item.available}</b><span>{item.bin}</span></div></article>):<p className="empty-copy">Inventory loads with the session.</p>}</div></aside>}
function History({snapshot}:{snapshot:Snapshot}){return <section className="history"><div className="section-head"><div><p>Durable record</p><h2>Completed picks</h2></div><span>{snapshot.history.length}</span></div>{snapshot.history.length?<div className="history-list">{snapshot.history.map((h,i)=><article key={h.operation_id??i}><span>✓</span><div><strong>{h.item?.name??h.name??h.sku}</strong><small>{h.quantity} picked {h.bin?`from ${h.bin}`:''}</small></div><time>{h.committed_at?formatTime(h.committed_at):''}</time></article>)}</div>:<p className="empty-copy">Confirmed picks will remain here, including after a reconnect.</p>}</section>}
function DeveloperPanel(p:{snapshot:Snapshot;demoEnabled:boolean;delay:number;setDelay:(n:number)=>void;ignoreCancellation:boolean;setIgnoreCancellation:(v:boolean)=>void;failure:string;setFailure:(v:string)=>void;inject:()=>void;close:()=>void}){const provider=p.snapshot.provider;return <div className="drawer-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)p.close()}}><aside className="developer" aria-label="Developer panel"><div className="drawer-head"><div><p>Session evidence</p><h2>Developer panel</h2></div><button onClick={p.close} aria-label="Close developer panel">×</button></div><dl><div><dt>Provider</dt><dd>{provider.name}</dd></div><div><dt>Status</dt><dd>{provider.status}</dd></div><div><dt>Model / voice</dt><dd>{[provider.model,provider.speaker].filter(Boolean).join(' / ')||'Not applicable'}</dd></div><div><dt>Language</dt><dd>{provider.language??'—'}</dd></div><div><dt>Measurement</dt><dd>{p.snapshot.mode==='fixture'?'Simulated playback only':'Audio measurements not collected; SDK playout estimates only'}</dd></div></dl>{p.demoEnabled&&<fieldset className="faults"><legend>Controlled failure injection</legend><label htmlFor="lookup-delay"><span>Lookup delay <output aria-hidden="true">{p.delay/1000}s</output></span></label><input id="lookup-delay" type="range" min="0" max="10000" step="500" value={p.delay} onChange={e=>p.setDelay(Number(e.target.value))}/><label className="check"><input type="checkbox" checked={p.ignoreCancellation} onChange={e=>p.setIgnoreCancellation(e.target.checked)}/>Return stale lookup after cancellation</label><label>Dependency failure<select value={p.failure} onChange={e=>p.setFailure(e.target.value)}><option value="">None</option><option value="lookup">Inventory lookup</option><option value="rime">Rime</option><option value="stt">Speech recognition</option><option value="llm">Language model</option></select></label><button onClick={p.inject}>Apply fault settings</button></fieldset>}<div className="event-log"><h3>Event timeline</h3>{p.snapshot.events.slice(-80).reverse().map(e=><article key={e.seq}><span>{e.seq}</span><div><strong>{e.type.replaceAll('_',' ')}</strong><small>{e.monotonic_ms.toFixed(1)} ms · epoch {e.response_epoch}</small></div><time>{formatTime(e.utc)}</time></article>)}</div></aside></div>}
function ErrorBanner({text}:{text:string}){return <div className="error-banner" role="alert"><span>!</span><p>{text}</p></div>}
function MicIcon({off}:{off:boolean}){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 15a4 4 0 0 0 4-4V6a4 4 0 0 0-8 0v5a4 4 0 0 0 4 4Zm7-4a7 7 0 0 1-12 4.9M5 11a7 7 0 0 0 7 7v3m-4 0h8M4 4l16 16" className={off?'slash':''}/></svg>}
